# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2
---
spec:
  inputs:
    release_version:
      description: |
        Version number, e.g. `1.2.3`. Must be in format `<major>.<minor>.<patch>`.
        Keep at `0.0.0` unless you're in the process of creating a release.
      type: string
      regex: ^([0]|([1-9]\d*))\.([0]|([1-9]\d*))\.([0]|([1-9]\d*))$
      default: 0.0.0
    release_issue:
      description: |
        The number of an issue which should be closed by a release MR created by this pipeline.
        Keep empty or unset unless you're in the process of creating a release.
      type: string
      regex: ^\d*$
      default: ''
---
image:
  name: git.opentalk.dev:5050/opentalk/backend/containers/rust:1.95.0-trixie
  pull_policy: if-not-present

stages:
  - lint
  - test
  - build
  - package
  - trigger
  - push
  - scan
  - release

.template_vars:
  FLAVORS: [intel, scratch]

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo
  # Enable one network per build for the test container and services
  FF_NETWORK_PER_BUILD: 'true'
  SKOPEO_IMAGE: quay.io/skopeo/stable:v1.20.0
  DEFAULT_FLAVOR: intel

.default_job_condition: &default_job_condition
  needs: []
  rules:
    # Run in merge requests (if there is one job with this instruction, all jobs without
    # it are ignored for the MR pipeline)
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Run on scheduled pipeline runs
    - if: $CI_PIPELINE_SOURCE == 'schedule'
    # Run on feature branches if there is no MR
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

.install_gstreamer_deps: &install_gstreamer_deps
  - >
    sed -i 's/^Components: main$/& contrib non-free non-free-firmware/'
    /etc/apt/sources.list.d/debian.sources
  - apt-get update
  - >
    apt-get update && apt-get install -y --no-install-recommends
    build-essential libssl-dev libbz2-dev
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev
    gstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad
    gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-vaapi libfdk-aac2 gstreamer1.0-fdkaac

include:
  - project: opentalk/ci/templates/collect-commit-evidence
    ref: v2
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/release-creation
    inputs:
      version: $[[ inputs.release_version ]]
      issue: $[[ inputs.release_issue]]
    ref: v1
    file: .gitlab-ci-template.yml
  - project: opentalk/ci/templates/changelog
    ref: v2
    file: .gitlab-ci-template.yml

lint:fmt:
  stage: lint
  <<: *default_job_condition
  before_script:
    - rustup component add rustfmt --toolchain nightly
  script:
    - cargo +nightly fmt -- --check

lint:clippy:
  stage: lint
  <<: *default_job_condition
  before_script:
    - *install_gstreamer_deps
  script:
    # Use clippy::pedantic for the entire source code
    # TODO: This it temporary and this rules will be added in the future
    - >
      cargo clippy --all-features
      -- --deny warnings --deny clippy::pedantic
      --allow clippy::cast-possible-truncation
      --allow clippy::cast-possible-wrap
      --allow clippy::cast-precision-loss
      --allow clippy::cast-sign-loss
      --allow clippy::doc-markdown
    # Use clippy::all for tests
    - >
      cargo clippy --all-features --tests
      -- --deny warnings --deny clippy::all

lint:dependency_check_advisories:
  stage: lint
  <<: *default_job_condition
  allow_failure: true
  script: cargo-deny check advisories --deny unmatched-skip --deny license-not-encountered

lint:dependency_check_bans_licenses_sources:
  stage: lint
  <<: *default_job_condition
  script: cargo-deny check bans licenses sources --deny unmatched-skip --deny license-not-encountered

lint:yaml:
  stage: lint
  <<: *default_job_condition
  image:
    name: alpine:3.23
    pull_policy: if-not-present
  before_script:
    - apk add --no-cache yamllint
  script: yamllint .

lint:toml:
  stage: lint
  <<: *default_job_condition
  script: taplo fmt --check

lint:unnecessary_dependencies:
  stage: lint
  <<: *default_job_condition
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  before_script: if ! cargo machete --version; then cargo install cargo-machete; fi
  script: cargo machete --with-metadata

lint:markdown:
  stage: lint
  <<: *default_job_condition
  image:
    name: registry.gitlab.com/pipeline-components/markdownlint:0.14.5
    pull_policy: if-not-present
  script:
    - mdl --style .markdown_style.rb  --warnings .

lint:licensing:
  stage: lint
  <<: *default_job_condition
  image:
    name: fsfe/reuse:latest
    entrypoint: ['']
    pull_policy: if-not-present
  script:
    - reuse lint

lint:commit:
  cache: {}
  image:
    name: node:lts-alpine
    pull_policy: if-not-present
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  variables:
    GIT_DEPTH: 250
  before_script:
    - apk add --no-cache git
    - npm install -g @commitlint/cli @commitlint/config-conventional
  script:
    - npx commitlint --from $CI_MERGE_REQUEST_DIFF_BASE_SHA --to HEAD --verbose

lint:justfile:
  stage: lint
  <<: *default_job_condition
  before_script: if ! just --version; then cargo install --root /usr/local just; fi
  script:
    # The `--fmt` command-line parameter is still unstable, but valuable anyway.
    - just --unstable --fmt --check

test:cargo_test:
  stage: test
  <<: *default_job_condition
  artifacts:
    paths:
      - target/coverage/html
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/coverage/cobertura.xml
  coverage: '/Coverage: \d+(?:\.\d+)?/'
  variables:
    COVERAGE_XML_PATH: 'concat("Coverage: ", 100 * string(//coverage/@line-rate), "%")'
    RUSTFLAGS: -Ctarget-feature=-crt-static -Cinstrument-coverage -Clink-arg=-fuse-ld=lld
    LLVM_PROFILE_FILE: ./target/coverage/raw/coverage-%p-%m.profraw
  before_script:
    - *install_gstreamer_deps
  script:
    # tests wetc_scenario1 is ignored until fixed
    - >
      cargo test
      --workspace
      --locked
      --
      --test-threads 1

    # Extract code coverage data
    - >
      grcov target/coverage/raw
      --binary-path ./target/debug/
      --source-dir .
      --output-types cobertura,html
      --branch
      --ignore-not-existing
      --ignore "*cargo*"
      --output-path target/coverage

    # Print out the coverage percentage for GitLab
    - xmllint --xpath "$COVERAGE_XML_PATH" target/coverage/cobertura.xml

test:doc:
  stage: test
  <<: *default_job_condition
  before_script:
    - *install_gstreamer_deps
  script:
    - cargo doc --workspace --verbose --no-deps

trigger-docs:
  stage: trigger
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PROJECT_NAME !~ /^.*canary$/ || $CI_COMMIT_TAG =~ /^v.*$/
  trigger:
    project: opentalk/backend/docs

build:docs:
  stage: build
  image:
    name: git.opentalk.dev:5050/opentalk/backend/containers/mkdocs-material:latest
    entrypoint: ['']
    pull_policy: if-not-present
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  artifacts:
    paths:
      - site/
  script:
    - mkdocs build --config-file "$CI_PROJECT_DIR"/mkdocs.yml --strict

package:container-mr:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  stage: package
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      when: manual
      allow_failure: true
  image:
    name: quay.io/buildah/stable:v1.43.1
    pull_policy: if-not-present
  before_script:
    - buildah login -u "$CI_REGISTRY_USER" --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - >
      IMAGE_TAG=$(
          echo -n "$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME" |
          tr -c '[:alnum:]_.-' '_' |
          sed 's/^[.-]/_/' |
          cut -c -63
      )
    - buildah build -f $CI_PROJECT_DIR/ci/Dockerfile-$FLAVOR -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG-$FLAVOR"
    - buildah push "$CI_REGISTRY_IMAGE:$IMAGE_TAG-$FLAVOR"

package:container:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  stage: package
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image:
    name: quay.io/buildah/stable:v1.43.1
    pull_policy: if-not-present
  before_script:
    - buildah login -u "$CI_REGISTRY_USER" --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - buildah build -f $CI_PROJECT_DIR/ci/Dockerfile-$FLAVOR -t  "$CI_REGISTRY_IMAGE:$FLAVOR-${CI_COMMIT_SHA:0:8}"
    - buildah push "$CI_REGISTRY_IMAGE:$FLAVOR-${CI_COMMIT_SHA:0:8}"

push:read-tags:
  stage: push
  needs: []
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
  image:
    name: alpine/git
    entrypoint: ['']
    pull_policy: if-not-present
  artifacts:
    reports:
      dotenv: package.env
  script:
    - git fetch --tags
    - TAGS=$(git tag --list | grep "^v[[:digit:]]\+\.[[:digit:]]\+\.[[:digit:]]\+.*$" | sort -V)
    - TAGS=$(echo "$TAGS" | head -n -1 | tr "\n" " ")
    - echo "TAGS=$TAGS" > package.env

push:container-create-and-push-tags:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  stage: push
  needs:
    - job: push:read-tags
      optional: true
    - job: package:container
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image:
    name: $SKOPEO_IMAGE
    entrypoint: ['']
    pull_policy: if-not-present
  script:
    - TAGS_TO_PUSH=$(./ci/create-container-tags.sh "${CI_COMMIT_TAG:-main}" "$TAGS" "$FLAVOR" "$DEFAULT_FLAVOR")
    - |
      for tag in $TAGS_TO_PUSH; do
        skopeo copy \
        --src-creds="${CI_REGISTRY_USER}":"${CI_REGISTRY_PASSWORD}" \
        --dest-creds="${CI_REGISTRY_USER}":"${CI_REGISTRY_PASSWORD}" \
        "docker://${CI_REGISTRY_IMAGE}:$FLAVOR-${CI_COMMIT_SHA:0:8}" "docker://${CI_REGISTRY_IMAGE}:$tag"
      done
    - echo "TAGS_$FLAVOR=$TAGS_TO_PUSH" > package.env
  artifacts:
    reports:
      dotenv: package.env

push-and-sign-images-to-harbor:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  needs:
    - push:container-create-and-push-tags
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+.*$/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: push
  variables:
    PIPELINE_FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE
    PIPELINE_NAMESPACE_SUFFIX: recorder
    PIPELINE_TAGS_ENV_NAME: TAGS_$FLAVOR
  trigger:
    project: opentalk/opentalk-devops/push-and-sign-images-for-the-opentalk-namespace
    strategy: depend
    forward:
      pipeline_variables: true

read-trivy-ignore-file:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  stage: scan
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - echo "TRIVY_IGNORE_STR_$FLAVOR=$(
      cat $CI_PROJECT_DIR/.trivyignore-$FLAVOR | sed -n 'H;${x;s/^\n//;s/\n/\\n/g;p}'
      )"  > package.env
  artifacts:
    reports:
      dotenv: package.env

container-scanning:
  parallel:
    matrix:
      - FLAVOR: !reference [.template_vars, FLAVORS]
  needs:
    - package:container
    - read-trivy-ignore-file
  rules:
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  stage: scan
  variables:
    PIPELINE_FULL_IMAGE_NAME: $CI_REGISTRY_IMAGE:dev-${FLAVOR}
    PIPELINE_PROJECT_WITH_NAMESPACE: $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    PIPELINE_ADDITIONAL_LABELS: team::media integration
    PIPELINE_TRIVY_IGNORE_FILE_STR_VAR: TRIVY_IGNORE_STR_${FLAVOR}
  trigger:
    project: opentalk/opentalk-devops/scan-container
    strategy: depend
    forward:
      pipeline_variables: true
