# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors = ["OpenTalk Team <mail@opentalk.eu>"]
edition = "2021"
homepage = "https://opentalk.eu/"
license = "EUPL-1.2"
name = "opentalk-recorder"
publish = false
repository = "https://gitlab.opencode.de/opentalk/recorder"
version = "0.0.0-dev"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bytes = "1"
compositor = { package = "opentalk-compositor", version = "0.9" }
config = { version = "0.14", default-features = false, features = ["toml"] }
env_logger = "0.11"
futures = "0.3"
gst = { package = "gstreamer", version = "0.23" }
lapin = { version = "2.3", default-features = false, features = ["rustls-webpki-roots-certs"] }
log = "0.4"
openidconnect = "3"
pin-project-lite = "0.2"
reqwest = { version = "0.11", default-features = false, features = ["json", "stream", "rustls-tls-native-roots"] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
sysinfo = "0.32"
thiserror = "1"
tokio-executor-trait = "2"
tokio-reactor-trait = "1"
tokio = { version = "1", features = ["rt-multi-thread", "time", "macros", "fs", "signal"] }
tt = { package = "tokio-tungstenite", version = "0.20", features = ["rustls-tls-webpki-roots"] }
types = { package = "opentalk-types", version = "0.25", features = ["rand", "serde"] }
types-common = { package = "opentalk-types-common", version = "0.25", features = ["rand", "serde"] }
types-control = { package = "opentalk-types-signaling-control", version = "0.25", features = ["serde"] }
types-signaling = { package = "opentalk-types-signaling", version = "0.25", features = ["rand", "serde"] }
types-signaling-livekit = { package = "opentalk-types-signaling-livekit", version = "0.25", features = ["serde"] }
types-signaling-recording = { package = "opentalk-types-signaling-recording", version = "0.25", features = ["serde"] }
types-signaling-recording-service = { package = "opentalk-types-signaling-recording-service", version = "0.25", features = ["serde"] }
urlencoding = "2.1"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26"
objc = "0.2.7"
