# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[package]
authors = ["OpenTalk Team <mail@opentalk.eu>"]
edition = "2021"
homepage = "https://opentalk.eu/"
license = "EUPL-1.2"
name = "opentalk-recorder"
publish = false
repository = "https://gitlab.opencode.de/opentalk/recorder"
version = "0.14.0"
build = "build.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
bytes = "1"
chrono = "0.4"
compositor = { package = "opentalk-compositor", version = "0.15.1" }
config = { version = "0.15", default-features = false, features = ["toml"] }
env_logger = "0.11"
futures = "0.3"
gst = { package = "gstreamer", version = "0.23" }
jsonwebtoken = "9.3"
lapin = { version = "2.3", default-features = false, features = [
  "rustls-webpki-roots-certs",
] }
log = "0.4"
openidconnect = "4"
pin-project-lite = "0.2"
reqwest = { version = "0.12", default-features = false, features = [
  "json",
  "stream",
  "rustls-tls-native-roots",
] }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
sysinfo = "0.35"
thiserror = "2"
tokio-executor-trait = "2"
tokio-reactor-trait = "1"
tokio = { version = "1", features = [
  "rt-multi-thread",
  "time",
  "macros",
  "fs",
  "signal",
] }
tt = { package = "tokio-tungstenite", version = "0.26", features = [
  "rustls-tls-webpki-roots",
] }
types-common = { package = "opentalk-types-common", version = "0.34", features = [
  "rand",
  "serde",
] }
types-control = { package = "opentalk-types-signaling-control", version = "0.35", features = [
  "serde",
] }
types-signaling = { package = "opentalk-types-signaling", version = "0.35", features = [
  "rand",
  "serde",
] }
types-signaling-livekit = { package = "opentalk-types-signaling-livekit", version = "0.35", features = [
  "serde",
] }
types-signaling-recording = { package = "opentalk-types-signaling-recording", version = "0.35", features = [
  "serde",
] }
types-signaling-recording-service = { package = "opentalk-types-signaling-recording-service", version = "0.35", features = [
  "serde",
] }
urlencoding = "2.1"
service-probe = "0.2"
clap = { version = "4.5.23", features = ["derive"] }
opentalk-version = "0.2.0"
directories = "6.0.0"
anstream = "0.6.18"
itertools = "0.14.0"
owo-colors = "4.2.0"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26"
objc = "0.2.7"

[build-dependencies]
anyhow = "1"
opentalk-version = "0.2.0"
