[package]
name = "k3k-recorder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compositor = { path = "compositor" }

gst = { package = "gstreamer", version = "0.19" }
gst-sdp = { package = "gstreamer-sdp", version = "0.19" }
gst-webrtc = { package = "gstreamer-webrtc", version = "0.19", features = [
    "v1_20",
] }
tt = { package = "tokio-tungstenite", version = "0.17", features = [
    "rustls-tls-webpki-roots",
] }
reqwest = { version = "0.11", default-features = false, features = [
    "json",
    "stream",
    "rustls-tls",
] }
config = "0.13"
env_logger = "0.10"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "time",
    "macros",
    "fs",
] }
#lapin = "2.1"
lapin = { version = "2.1", default-features = false,  features = [ "rustls-webpki-roots-certs" ] }
tokio-reactor-trait = "1"
tokio-executor-trait = "2"
futures = "0.3"
log = "0.4"
serde_json = "1"
rand = "0.8"
uuid = { features = ["serde"], version = "1" }
bytes = "1"
thiserror = "1"
openidconnect = "2.3"
tempfile = "3"
pin-project-lite = "0.2.9"

[workspace]
members = ["compositor"]
