[auth]
issuer = "https://p01nc.heinlein-video.de:8443/auth/realms/K3K"
client_id = "Obelisk"
client_secret = "nun7pm3Imju9S4efHy9nLKtUWsSLXIyR"

[controller]
domain = "localhost:8000"
insecure = true

[rabbitmq]
uri = "amqp://guest:guest@p01nc.heinlein-video.de/%2F"
queue = "recorder"
