[auth]
issuer = "https://accounts.testing.opentalk.eu/auth/realms/K3K"
client_id = "Obelisk"
client_secret = "INSERT_KEY"

[controller]
domain = "controller.testing.opentalk.eu"
insecure = false

[rabbitmq]
uri = "amqp://guest:guest@p01nc.heinlein-video.de/%2F"
queue = "recorder"
