# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[monitoring]
port = 11411

[auth]
# Note:
# The Recorder client must be a service account
# with the _service account role_ "opentalk-recorder"
client_id = "Recorder"
client_secret = "INSERT_KEY"
issuer = "http://localhost:8080/auth/realms/MyRealm"

[controller]
domain = "localhost:11311"
insecure = true

# Optional orchestrator configuration
#[orchestrator]
# The API key of the orchestrator
#api_key = { id = "orchestrator", secret = "secret" }
# The orchestrator URL
#url = "http://127.0.0.1:11222"

[http]
# The host to bind the HTTP Server to (defaults to 0.0.0.0).
host = "0.0.0.0"
# The port to bind the HTTP Server to (defaults to 11311).
port = "5555"

# The api keys for internal service endpoints
#
# The recorder can have multiple api keys configured. An api key can be configured as string ("<key_id>:<key_secret>")
# or as key/value pair ({id = "<key_id>", secret = "<key_secret>"}).
api_keys = [{ id = "recorder", secret = "secret" }]

[recorder]
# Shows a display sink, for debug purpose
display = true

# see `man strftime`
# European style - alpine with musl has no locale
clock_format = "%d.%m.%y %X %Z"

# US style
#clock_format = "%x %X %Z"

# Enables Hardware Acceleration for Intel GPUs
#[recorder.hardware_acceleration]
#manufacturer = "intel"
#device = "/dev/dri/renderD129"
