# SPDX-FileCopyrightText: OpenTalk GmbH <mail@opentalk.eu>
#
# SPDX-License-Identifier: EUPL-1.2

[monitoring]
port = 11411

[auth]
# Note:
# The Recorder client must be a service account
# with the _service account role_ "opentalk-recorder"
issuer = "http://localhost:8080/auth/realms/MyRealm"
client_id = "Recorder"
client_secret = "INSERT_KEY"

[controller]
domain = "localhost:11311"
insecure = true

[rabbitmq]
uri = "amqp://username:password@localhost/%2F"
queue = "recorder"

[recorder]
# Shows a display sink, for debug purpose
display = true

# see `man strftime`
# European style - alpine with musl has no locale
clock_format = "%d.%m.%y %X %Z"

# US style
#clock_format = "%x %X %Z"

# Enables Hardware Acceleration for Intel GPUs
#[recorder.hardware_acceleration]
#manufacturer = "intel"
#device = "/dev/dri/renderD129"
