[package]
name = "compositor"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gst = { package = "gstreamer", version = "0.19", features = ["v1_20"] }
gst-sdp = { package = "gstreamer-sdp", version = "0.19" }
gst-webrtc = { package = "gstreamer-webrtc", version = "0.19", features = [
    "v1_20",
] }
log = "0.4.0"
glib = "0.16"
tokio = { version = "1", features = ["sync", "net"] }
inotify = "0.10"
tempfile = "3"
thiserror = "1"

[dev-dependencies]
env_logger = "0.9.0"
